version: '3.8'
services:
  # app service
  app:
    container_name: backend
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      DATABASE_NAME: crud-item
      DATABASE_USER: root
      DATABASE_PASS: root
      DATABASE_URI: mongodb://database:27017
    ports:
      - '3000:3000'
    depends_on:
      - database

  # start the mongodb service as container
  database:
    image: mongo:7.0
    container_name: mongodb
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root